lib/mentor_finder_web/router.ex
defmodule MentorFinderWeb.Router do
  use MentorFinderWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MentorFinderWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MentorFinderWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/", PageLive, :index

    live_dashboard "/_dashboard", metrics: MentorFinderWeb.Telemetry
  end

  # Other scopes may use custom stacks.
  # scope "/api", MentorFinderWeb do
  #   pipe_through :api
  # end

  ## Authentication routes

  scope "/", MentorFinderWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log-in", UserSessionController, :new
    post "/users/log-in", UserSessionController, :create
    get "/users/reset-password", UserResetPasswordController, :new
    post "/users/reset-password", UserResetPasswordController, :create
    get "/users/reset-password/:token", UserResetPasswordController, :edit
    put "/users/reset-password/:token", UserResetPasswordController, :update
  end

  scope "/", MentorFinderWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update-password", UserSettingsController, :update_password
    put "/users/settings/update-email", UserSettingsController, :update_email
    get "/users/settings/confirm-email/:token", UserSettingsController, :confirm_email
  end

  scope "/", MentorFinderWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/mentor_finder_web/controllers/user_session_controller.ex
defmodule MentorFinderWeb.UserSessionController do
  use MentorFinderWeb, :controller

  alias MentorFinder.Accounts
  alias MentorFinderWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      render(conn, "new.html", error_message: "Invalid e-mail or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/mentor_finder_web/views/user_session_view.ex
defmodule MentorFinderWeb.UserSessionView do
  use MentorFinderWeb, :view
end

lib/mentor_finder_web/templates/user_session/new.html.eex
<h1>Log in</h1>

<%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user], fn f -> %>
  <%= if @error_message do %>
    <div class="alert alert-danger">
      <p><%= @error_message %></p>
    </div>
  <% end %>

  <%= label f, :email %>
  <%= email_input f, :email, required: true %>

  <%= label f, :password %>
  <%= password_input f, :password, required: true %>

  <%= label f, :remember_me, "Keep me logged in for 60 days" %>
  <%= checkbox f, :remember_me %>

  <div>
    <%= submit "Log in" %>
  </div>
<% end %>

<p>
  <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
</p>